name: manage_calendar_events
description: A flutter plugin which will help you to add, edit and remove the events (with reminders) from your (Android and ios) calendars
version: 1.0.1
author: lakshmanaprabhu <r.lakshmanaprabhu@ymail.com>
homepage: https://github.com/lakshmanaprabhu/manage_calendar_events

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.fantastic.manage_calendar_events
    pluginClass: ManageCalendarEventsPlugin

